import {
  Award,
  Brain,
  Calendar,
  CheckCircle,
  Clock,
  Compass,
  Crown,
  Eye,
  Flame,
  Footprints,
  Gem,
  Infinity,
  Medal,
  Rocket,
  Search,
  Shield,
  ShieldCheck,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  Trophy,
  UserCircle,
  Zap,
  LucideIcon,
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  footsteps: Footprints,
  rocket: Rocket,
  compass: Compass,
  calendar: Calendar,
  search: Search,
  'user-circle': UserCircle,
  zap: Zap,
  clock: Clock,
  award: Award,
  target: Target,
  trophy: Trophy,
  medal: Medal,
  'check-circle': CheckCircle,
  star: Star,
  brain: Brain,
  shield: Shield,
  crown: Crown,
  gem: Gem,
  sparkles: Sparkles,
  flame: Flame,
  'trending-up': TrendingUp,
  infinity: Infinity,
  'shield-check': ShieldCheck,
  eye: Eye,
};

export const getIcon = (iconName: string): LucideIcon => {
  return iconMap[iconName] || Award;
};

